export const CLASSES = {
  DEATH_KNIGHT: 'DEATH_KNIGHT',
  DEMON_HUNTER: 'DEMON_HUNTER',
  DRUID: 'DRUID',
  HUNTER: 'HUNTER',
  MAGE: 'MAGE',
  PALADIN: 'PALADIN',
  PRIEST: 'PRIEST',
  ROGUE: 'ROGUE',
  SHAMAN: 'SHAMAN',
  WARLOCK: 'WARLOCK',
  WARRIOR: 'WARRIOR',
}

export const STATES = {
  START: 'START',
  SETTINGS: 'SETTINGS',
  CLASSES: 'CLASSES',
}
